<a href="https://colab.research.google.com/github/Geysa-Ribeiro/machineLearning_2026/blob/main/AulaMachineLearning_2403.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introdução a Python

In [ ]:
a = 10
b = 5
soma = a + b
print(soma)

15

#Segunda Camada

In [ ]:
c = 7
d = 3
print(c * d)

21

#Bibliotecas e Funções em Python

In [ ]:
import math

def equacao2grau(a,b,c):
  delta = b * b - 4*a*c

  if(delta < 0):
    return 'Número sem raíz', delta

  x1 = (-b + math.sqrt(delta)) /(2*a)
  x2 = (-b - math.sqrt(delta)) /(2*a)

  return x1, x2

#Testes de Função Matemática

In [ ]:
eq = equacao2grau(1,-3,2)
print(eq)

(2.0, 1.0)

In [ ]:
import random
for i in range(5):
  a = random.randint(-5,5)
  b = random.randint(-10,10)
  c = random.randint(-10,10)
  eq += equacao2grau(a,b,c)

In [ ]:
for i in range(12):
  if(i % 2 == 0):
    if (eq[i] != 'Número sem raíz'):
      print('X1: [',f"{eq[i]:.2f}",']')
    else:
      if(eq[i] != 'Número sem raíz'):
        print('X2: [',f"{eq[i]:.2f}",']')

X1: [ 2.00 ]
X1: [ -3.30 ]
X1: [ 1.00 ]
X1: [ 0.50 ]

#Trabalhando com Dados Externos

#Bibliotecas de uso da pipeline

In [2]:
!pip -q install plotly
!pip -q install yellowbrick

In [3]:
import pandas as pd
import plotly.express as px
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [12]:
base_credit = pd.read_csv('/content/drive/MyDrive/AM_t4/credit_data.csv')

In [15]:
base_credit.head(10)

   clientid        income        age         loan  default
0         1  66155.925095  59.017015  8106.532131        0
1         2  34415.153966  48.117153  6564.745018        0
2         3  57317.170063  63.108049  8020.953296        0
3         4  42709.534201  45.751972  6103.642260        0
4         5  66952.688845  18.584336  8770.099235        1
5         6  24904.064140  57.471607    15.498598        0
6         7  48430.359613  26.809132  5722.581981        0
7         8  24500.141984  32.897548  2971.003310        1
8         9  40654.892537  55.496853  4755.825280        0
9        10  25075.872771  39.776378  1409.230371        0

In [16]:
base_credit[base_credit['loan'] <= 1.377630]

     clientid        income        age     loan  default
865       866  28072.604355  54.142548  1.37763        0

#Análises de Anomalias Exploratórias

##Análise de Anomalia Negativa

In [18]:
base_credit.loc[base_credit['age'] < 0]

    clientid        income        age         loan  default
15        16  50501.726689 -28.218361  3977.287432        0
21        22  32197.620701 -52.423280  4244.057136        0
26        27  63287.038908 -36.496976  9595.286289        0